Redditclone/config/routes.rb
Rails.application.routes.draw do
  resources :users, only: [:new, :create]
  resources :subs
  resources :posts do
    resources :comments, only: [:new]
    member do
      get 'upvote'
      get 'downvote'
    end
  end
  resources :comments, only: [:create, :show] do
    member do
      get 'upvote'
      get 'downvote'
    end
  end
  resource :session, only: [:new, :create, :destroy]
end

Redditclone/app/models/comment.rb
class Comment < ActiveRecord::Base
  include Votable
  validates :author_id, :post_id, :content, presence: true

  belongs_to(
    :author,
    class_name: 'User',
    foreign_key: :author_id
  )

  belongs_to :post

  belongs_to(
    :parent_comment,
    class_name: 'Comment',
    foreign_key: :parent_comment_id
  )

  has_many(
    :child_comments,
    class_name: 'Comment',
    foreign_key: :parent_comment_id
  )
end

Redditclone/app/models/concerns/votable.rb
module Votable
  extend ActiveSupport::Concern

  included do
    has_many :votes, as: :votable, dependent: :destroy
  end

  def total_votes
    votes.map(&:value).inject(:+)
  end

end

Redditclone/app/models/post.rb
class Post < ActiveRecord::Base
  include Votable

  validates :title, :author_id, presence: true

  has_many :post_subs, inverse_of: :post

  has_many :subs, through: :post_subs

  has_many :comments

  belongs_to(
    :author,
    class_name: "User",
    foreign_key: :author_id,
    primary_key: :id
  )

  def top_level_comments
    self.comments.where(parent_comment_id: nil)
  end

  def comments_by_parent_id
    comment_hash = Hash.new { |h, k| h[k] = [] }
    self.comments.each do |comment|
      comment_hash[comment.parent_comment_id] << comment
    end
    comment_hash
  end
end

Redditclone/app/models/post_sub.rb
class PostSub < ActiveRecord::Base
  self.table_name = "posts_subs"

  validates :sub_id, presence: true

  belongs_to :post, inverse_of: :post_subs
  belongs_to :sub, inverse_of: :post_subs
end

Redditclone/app/models/sub.rb
class Sub < ActiveRecord::Base
  validates :title, :description, :moderator_id, presence: true
  validates :title, uniqueness: true

  has_many :post_subs, inverse_of: :sub
  has_many :posts, through: :post_subs

  belongs_to(
    :moderator,
    class_name: 'User',
    foreign_key: :moderator_id)
end

# post = Post.find(xxxxxx)
# subs = post.sub_ids

Redditclone/app/models/user.rb
class User < ActiveRecord::Base
  validates :name, :password_digest, :session_token, presence: true
  validates :name, :session_token, uniqueness: true

  after_initialize :ensure_session_token

  has_many :subs

  def self.find_by_credentials(user, password)
    user = User.find_by_name(user)
    if user.nil?
      return nil
    else
      user.is_password?(password) ? user : nil
    end
  end

  def password=(password)
    self.password_digest = BCrypt::Password.create(password)
  end

  def ensure_session_token
    self.session_token ||= generate_session_token
  end

  def reset_session_token!
    self.session_token = generate_session_token
    self.save!
    self.session_token
  end

  def is_password?(password)
    BCrypt::Password.new(self.password_digest).is_password?(password)
  end



  private

  def generate_session_token
    SecureRandom.urlsafe_base64
  end
end

Redditclone/app/models/vote.rb
class Vote < ActiveRecord::Base
  validates :value, inclusion: { in: [1, -1] }
  validates :votable_type, inclusion: { in: %w(post comment) }
  validates :value, :votable_id, :votable_type, presence: true

  belongs_to :votable, polymorphic: true
end

Redditclone/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  helper_method :logged_in?, :current_user

  def ensure_logged_in
    redirect_to new_session_url unless logged_in?
  end



  def log_in!(user)
    @current_user = user
    session[:session_token] = @current_user.reset_session_token!
  end

  def log_out!
    current_user.reset_session_token!
    @current_user = nil
    session[:session_token] = nil
  end

  def current_user
    @current_user = User.find_by(session_token: session[:session_token])
  end

  def logged_in?
    !!current_user
  end


end

Redditclone/app/controllers/comments_controller.rb
class CommentsController < ApplicationController

  def new
    @comment = Comment.new
    @post_id = params[:post_id]
    render :new
  end

  def create
    @comment = Comment.new(comment_params)
    @comment.author_id = current_user.id
    if @comment.save
      redirect_to post_url(comment_params[:post_id])
    else
      flash[:errors] = @comment.errors.full_messages
      render :new
    end
  end

  def show
    @comment = Comment.find(params[:id])
  end

  private

  def comment_params
    params.require(:comment).permit(:content, :post_id, :parent_comment_id)
  end
end

Redditclone/app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :ensure_correct_author, only: [:edit, :update]

  def new
    @post = Post.new

  end

  def create
    @post = Post.new(post_params)
    @post.author_id = current_user.id
    # @post.post_subs = params[:sub_ids]
    # fail
    if @post.save
      render :show
    else
      flash[:errors] = @post.errors.full_messages
      render :new
    end
  end

  # def edit
  #
  #   render :edit
  # end

  def update

    if @post.update(post_params)
      render :show
    else
      flash[:errors] = @post.errors.full_messages
      render :edit
    end
  end

  def destroy

  end

  def show
    @post = Post.find(params[:id])
    @comment_hash = @post.comments_by_parent_id
  end

  def ensure_correct_author
    @post = Post.find(params[:id])
    redirect_to subs_url unless @post.author_id == current_user.id
  end

  private
  def post_params
    params.require(:post).permit(:title, :url, :content, sub_ids: [])
  end


end

Redditclone/app/controllers/sessions_controller.rb
class SessionsController < ApplicationController


  def create
    @user = User.find_by_credentials(params[:session][:name],params[:session][:password])
    log_in!(@user)
    render text: "logged in"
  end

  def destroy
    log_out!
    render :new
  end
end

Redditclone/app/controllers/subs_controller.rb
class SubsController < ApplicationController
  before_action :ensure_logged_in, only: [:new, :create, :edit, :update]

  def index
    @subs = Sub.all
  end

  def new
    @sub = Sub.new
    render :new
  end

  def create
    @sub = Sub.new(sub_params)
    @sub.moderator_id = current_user.id
    if @sub.save
      render :show
    else
      flash[:errors] = @sub.errors.full_messages
      render :new
    end
  end

  def edit
    @sub = Sub.find(params[:id])
    render :edit
  end

  def update
    @sub = Sub.find(params[:id])
    if @sub.update(sub_params)
      render :show
    else
      flash[:errors] = @sub.errors.full_messages
    end
  end

  def show
    @sub = Sub.find(params[:id])
    render :show
  end



  private

  def sub_params
    params.require(:sub).permit(:title, :description)
  end
end

Redditclone/app/controllers/users_controller.rb
class UsersController < ApplicationController
  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    if @user.save
      render text: "User created!"
      log_in!(@user)
    else
      flash[:errors] = @user.errors.full_messages
      render :new
    end
  end


  private

  def user_params
    params.require(:user).permit([:name, :password])
  end
end

Redditclone/app/helpers/application_helper.rb
module ApplicationHelper
  def auth_token_input
    str = <<-HTML
      <input type="hidden" name="authenticity_token" value="#{form_authenticity_token}">
    HTML
    str.html_safe
  end

  def method_input(method)
    str = <<-HTML
      <input type="hidden" name="_method" value="#{method}">
    HTML

    str.html_safe
  end
  
end

Redditclone/app/helpers/comments_helper.rb
module CommentsHelper
end

Redditclone/app/helpers/posts_helper.rb
module PostsHelper
end

Redditclone/app/helpers/sessions_helper.rb
module SessionsHelper
end

Redditclone/app/helpers/subs_helper.rb
module SubsHelper
end

Redditclone/app/views/comments/_comment.html.erb
<ul>
<%=comment.content %> - <%= comment.author.name %> at <%= comment.created_at %>
Total votes: <%= comment.total_votes %>

<% @comment_hash[comment.id].each do |child| %>
  <%= render "comments/comment", comment: child %>
<% end %>
</ul>

Redditclone/app/views/comments/_form.html.erb
<form id="form_id" action="/comments" method="post">
  <%= auth_token_input %>
  <input type="hidden" name="comment[post_id]" value="<%= post_id %>">


  <% if parent_comment_id %>
    <input type="hidden" name="comment[parent_comment_id]" value="<%= parent_comment_id %>">
  <% end %>

  <textarea name="comment[content]" rows="8" cols="40"></textarea>
  <input type="submit" value="Post comment">
</form>

Redditclone/app/views/comments/new.html.erb
<h2>Add a comment</h2>

<%= render "form" %>

Redditclone/app/views/comments/show.html.erb
<h2>Reply</h2>

<%= @comment.content %>

<br>

<%= render "form", parent_comment_id: @comment.id, post_id: @comment.post_id %>

Redditclone/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>RedditClone</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

  <% if flash[:errors]%>
    <% flash[:errors].each do |error|%>
      <%= error %>
    <% end %>
  <%end%>


  <% if logged_in? %>
    <h2><%= "Hello, #{current_user.name}!" %></h2>
    <br>
    <form id="form_id" action="<%= session_url %>" method="post">
      <%= method_input("delete") %>
      <%= auth_token_input %>
      <input type="submit" value="Log Out">

    </form>
  <% end %>

<%= yield %>

</body>
</html>

Redditclone/app/views/subs/_form.html.erb
<form action="<%= url %>" method="POST">
  <%=auth_token_input%>
  <% if action == :edit %>
    <%=method_input("PATCH")%>
  <%end%>

  <label> Sub Name </label>
  <input type="text" name="sub[title]" value="<%=sub.title%>">

  <label> Description </label>
  <textarea name="sub[description]"><%=sub.description%></textarea>

    <input type="submit" value="Submit">

</form>

Redditclone/app/views/subs/edit.html.erb
<h2>Edit your sub</h2>

<%= render "form", url: sub_url(@sub), sub: @sub, action: :edit%>

Redditclone/app/views/subs/index.html.erb
<br>
<% @subs.each do |sub| %>
  <a href="<%= sub_url(sub) %>"><strong><%= sub.title %></strong></a>
  <br>
  <%= sub.description %>
  <br>
<% end %>

Redditclone/app/views/subs/new.html.erb
<h2>Submit a Sub</h2>

<%= render "form", url: subs_url, sub: @sub, action: :new%>

Redditclone/app/views/subs/show.html.erb
<h2><%= @sub.title %></h2>

<br>
<%= @sub.description %>
<br><br>
Moderator: <%= @sub.moderator.name %>
<br>
<a href="<%= edit_sub_url(@sub) %>">Edit this sub</a>